# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: get_market_candles.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import basic_message_info_pb2 as basic__message__info__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='get_market_candles.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x18get_market_candles.proto\x1a\x18\x62\x61sic_message_info.proto\"}\n\x10GetMarketCandles\x12-\n\x12\x62\x61sic_message_info\x18\x01 \x01(\x0b\x32\x11.BasicMessageInfo\x12\x0c\n\x04\x66igi\x18\x02 \x01(\t\x12\r\n\x05\x66rom_\x18\x03 \x01(\t\x12\x0b\n\x03to_\x18\x04 \x01(\t\x12\x10\n\x08interval\x18\x05 \x01(\tb\x06proto3'
  ,
  dependencies=[basic__message__info__pb2.DESCRIPTOR,])




_GETMARKETCANDLES = _descriptor.Descriptor(
  name='GetMarketCandles',
  full_name='GetMarketCandles',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='basic_message_info', full_name='GetMarketCandles.basic_message_info', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='figi', full_name='GetMarketCandles.figi', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='from_', full_name='GetMarketCandles.from_', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='to_', full_name='GetMarketCandles.to_', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='interval', full_name='GetMarketCandles.interval', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=179,
)

_GETMARKETCANDLES.fields_by_name['basic_message_info'].message_type = basic__message__info__pb2._BASICMESSAGEINFO
DESCRIPTOR.message_types_by_name['GetMarketCandles'] = _GETMARKETCANDLES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetMarketCandles = _reflection.GeneratedProtocolMessageType('GetMarketCandles', (_message.Message,), {
  'DESCRIPTOR' : _GETMARKETCANDLES,
  '__module__' : 'get_market_candles_pb2'
  # @@protoc_insertion_point(class_scope:GetMarketCandles)
  })
_sym_db.RegisterMessage(GetMarketCandles)


# @@protoc_insertion_point(module_scope)
