version: '3.1'

services:
  producer:
    build: ./connector
    environment:
      KAFKA_BROKER_ADRES: kafka-broker:9092

  consumer:
    build: ./consumer
    environment:
      KAFKA_BROKER_ADRES: kafka-broker:9092

networks:
  default:
    external:
      name: kafka-network
