version: '3'

services:

  producer:
    build: ./producer
    environment:
      KAFKA_BROKER_ADRES: kafka-broker:9092

  consumer:
    build: ./consumer
    environment:
      KAFKA_BROKER_ADRES: kafka-broker:9092

networks:
  default:
    external:
      name: kafka-network