version: '3'

services:

  connector:
    build:
      context: ../
      dockerfile: ./service2/Dockerfile
    environment:
      KAFKA_BROKER_ADRESS: kafka-broker:9092

networks:
  default:
    external:
      name: kafka-network