version: '3'

services:

  connector:
    build:
      context: ../
      dockerfile: ./connector/Dockerfile
    environment:
      KAFKA_BROKER_ADRESS: kafka-broker:9092
    env_file:
      - tokens.env

networks:
  default:
    external:
      name: kafka-network